/// <reference types="Cypress" />

describe('make lotsa connectionz', ()=>{
    it('will login to linkedin', ()=>{
        cy.visit("https://www.linkedin.com/login")
        // cy.get('.nav__button-secondary').click()
        cy.contains('Stay updated on your professional world').should("be.visible")
        // cy.get('.login__form > .btn__tertiary--medium').click()
        cy.get('#username').type("samkahunga65@gmail.com")
        cy.get('#password').type("77AAllpphhaa1111")
        cy.get('.btn__primary--large').click()
        cy.wait(3000)
        cy.get('.profile-rail-card__actor-link').click()
        cy.wait(3000)
        cy.get('ul[class="pv-profile-pymk__list"]')
        .find('li')
        .find('button').click({multiple:true})
        cy.get('.global-nav__logo > g > path').click()
        cy.get('.profile-rail-card__actor-link').click()
        cy.wait(3000)
        cy.get('ul[class="pv-profile-pymk__list"]')
        .find('li')
        .find('button').click({multiple:true})
        cy.get('.global-nav__logo > g > path').click()
        cy.get('.profile-rail-card__actor-link').click()
        cy.wait(3000)
        cy.get('ul[class="pv-profile-pymk__list"]')
        .find('li')
        .find('button').click({multiple:true})
        cy.get('.global-nav__logo > g > path').click()
        cy.get('.profile-rail-card__actor-link').click()
        cy.wait(3000)
        cy.get('ul[class="pv-profile-pymk__list"]')
        .find('li')
        .find('button').click({multiple:true})
        cy.get('.global-nav__logo > g > path').click()
        cy.get('.profile-rail-card__actor-link').click()
        cy.wait(3000)
        cy.get('ul[class="pv-profile-pymk__list"]')
        .find('li')
        .find('button').click({multiple:true})
        cy.get('.global-nav__logo > g > path').click()
        cy.get('.profile-rail-card__actor-link').click()
        cy.wait(3000)
        cy.get('ul[class="pv-profile-pymk__list"]')
        .find('li')
        .find('button').click({multiple:true})
        cy.get('.global-nav__logo > g > path').click()
        cy.get('.profile-rail-card__actor-link').click()

        
    })
})